# Generated by Django 2.0.2 on 2018-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181116_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
