# Generated by Django 2.0.2 on 2018-11-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181116_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Page'),
        ),
    ]
